#!/bin/sh -efu

# Don't run if the package is not installed
dpkg -l 'ifupdown-qinq' | grep -q '^ii' || exit 0

if [ -z "${IFACE:-}" ]; then
    echo "No IFACE value is set" >&2
    exit 1
fi

case "$IFACE" in
    *.*.*)
        vlans="${IFACE#*.}"
        IF_QINQ_SERVICE_VLAN="${vlans%%.*}"

        if [ -z "${IF_QINQ_TRUNK_IFACE:-}" ]; then
            IF_QINQ_TRUNK_IFACE="${IFACE%%.*}"
        fi
        
        if [ -z "${IF_QINQ_SERVICE_IFACE:-}" ]; then
            IF_QINQ_SERVICE_IFACE="${IFACE%%.*}.$IF_QINQ_SERVICE_VLAN"
        fi
        ;;
esac

# Use qinq_trunk_port parameter as a flag determining if this
# script should be executed.
[ -n "${IF_QINQ_TRUNK_IFACE:-}" ] || exit 0

if [ -z "${IF_QINQ_SERVICE_IFACE:-}" ]; then
    echo "Service VLAN interface name is not set. Use the \"name.ID1.ID2\" interface naming scheme or specify the \"qinq_service_iface\" configuration parameter value" >&2
    exit 1
fi

echo "Bringing down and removing the service VLAN interface ${IF_QINQ_SERVICE_IFACE}..." >&2
ip link set "$IF_QINQ_SERVICE_IFACE" down
ip link del "$IF_QINQ_SERVICE_IFACE"

echo "Bringing down the trunk interface ${IF_QINQ_TRUNK_IFACE}..." >&2
ip link set "$IF_QINQ_TRUNK_IFACE" down
